updated Docker file and Makefile

diff --git a/iws/Dockerfile b/iws/Dockerfile
--- a/iws/Dockerfile
+++ b/iws/Dockerfile
@@ -1,24 +1,38 @@
-# Layer - 1
-FROM python:3.12 as build
-WORKDIR /app
-RUN python -m venv --upgrade-deps venv
-COPY requirements.txt requirements.txt
-RUN venv/bin/pip install -r requirements.txt
+#FROM public.ecr.aws/docker/library/python:3.12.7-slim
+#Specifies the Python base image.
+FROM python:3.12-slim
 
-# Layer - 2
-FROM python:3.12-slim as deploy
-RUN useradd app-user
-USER app-user
-EXPOSE 8000
-ENV PATH=/opt/venv/bin:$PATH \
-    FLASK_APP=posts
-USER root
-COPY --from=build /opt/venv /opt/venv
+# Arguments
+ARG APP_ENV=develop
+ARG API_ENV=develop
+
+# Define Env Variables
+ENV APP_ENV=$APP_ENV
+ENV API_ENV=$API_ENV
+ENV APP_NAME=iws_posts
+
+# Sets the working directory inside the Docker container at `/app`
 WORKDIR /app
-COPY --chown=1000:1000 . app-user
-RUN venv/bin/pip install -e app-user
-COPY gunicorn.conf.py .
-USER app-user
+
+# Copies the current directory (.) from the host machine to the `/app` directory in the Docker container.
+COPY . /app
+#COPY requirements.txt .
+
+# Installs the Python dependencies specified in the `requirements.txt` file.
+RUN pip install --upgrade pip
+#RUN pip install -r requirements.txt
+#RUN pip install --no-cache-dir -r requirements.txt
+RUN pip install -r requirements.txt --no-cache-dir
+
+# Copy the rest of your application code into the container at /app
+#COPY . .
+
+# EXPOSE is for documentation only - does not do anything
+# 8082 is the default port the server is listening on
+EXPOSE 8080
+#HEALTHCHECK --interval=15s --timeout=5s --start-period=5s --retries=3 CMD  curl --silent --fail 0.0.0.0:8082/health_check || exit 1
 
 # gunicorn -c gunicorn.conf.py wsgi:app
 CMD ["gunicorn", "-c", "gunicorn.conf.py", "wsgi:app"]
+#python -m flask --app wsgi run --port 8080 --debug
+#CMD ["python", "-m", "flask", "--app", "wsgi", "run", "--port", "8080", "--debug"]
